apiVersion: v1
kind: PersistentVolume
metadata: 
  name: grafana-pv 
  namespace: monitoring 
  labels: 
    type: local
spec: 
  storageClassName: manual 
  capacity: 
    storage: 1Gi 
  accessModes: 
    - ReadWriteOnce 
  hostPath: 
    path: "/mnt/data/grafana"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: grafana-pvc 
  namespace: monitoring
spec: 
  storageClassName: manual 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi
  selector: 
    matchLabels: 
      type: local
